<?php

return [
    'admin' => [
        'username' => env('ADMIN_USERNAME', 'Philemon'),
        'password' => env('ADMIN_PASSWORD', 'Philemon@123'),
    ],
    'organization' => [
        'name' => 'Building Families and Community Global Trust',
        'short_name' => 'BFC Global Trust',
        'tagline' => 'Building families. Touching communities. Changing the world.',
        'mission' => 'To equip families with the transforming knowledge of Christian discipleship for influence to the community near them and the nations of the world.',
        'vision' => 'To raise and establish strong and healthy disciples of Jesus Christ in families who will influence the community around them and the nations of the world.',
        'vision_statement' => 'Building families, Touching Communities, Changing the World.',
        'about_intro' => 'Building Families and Community Global Trust is a non-denominational Christian fellowship that mobilizes, facilitates deliberations, training, and equipping for families, parents, young people, Christian leaders, and the church to return to the heart of God for families and community for global transformation through the Gospel of Jesus Christ integrated in the discipleship process.',
        'about_summary' => 'Our strategies emphasize restoring discipleship into the context of the family. We have developed practical ways to engage young people in learning institutions, the corporate space, marriage and family, and the local church to communicate this message.',
        'founders_message' => [
            'title' => 'Message of the Founders',
            'signature' => 'Philemon & Faith - Founders & Directors',
            'image' => 'https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=900&q=80',
            'paragraphs' => [
                'Greetings in the Lord\'s name! We thank God for the fruitful marriage for 13 years now. God has blessed us with three amazing children, Sarah Mshindi, Levi Wema, and Sifa Hadassah. We homeschool our children with a desire to establish them to be disciples of Christ.',
                'We attended discipleship training in different seasons after our high school education, and that has proved pivotal in our Christian living and ministry. This shaped our perspectives and anchored in us a desire to honor and glorify God.',
                'We have worked in discipleship ministry in different contexts in Kenya among the youth for more than a decade. Generation Impact Ministry in Kenya was very instrumental in helping us learn the principles of discipleship as we worked with the ministry team from January 2016 to November 2024.',
                'At the end of 2024, we deeply felt drawn by the Lord to take a sabbatical for prayer and rest for a year. During this season, as we sought God for direction for our next phase of ministry, there was an increasing burden toward a ministry that would integrate discipleship within the context of the family.',
                'One consistent word that appeared to us in our season of prayer was "BUILD", traceable in many parts of the Bible but especially in Nehemiah\'s context. Building takes resilience, courage, and patience. We desire to partner with God\'s children locally and around the globe to build strong and healthy families.',
                'We invite you to join us in the mobilization of the church, young people, and families as we equip more workers for this noble task and responsibility.',
            ],
        ],
        'about_themes' => [
            [
                'title' => 'Build',
                'description' => 'As we bring these reflections into the light, we think of the theme of building, presented extensively in the Bible in both the Old and New Testament. Nehemiah responded in brokenness, rallied the royal family and God\'s people, and rebuilt the broken walls of Jerusalem. (Neh. 1:4)',
            ],
            [
                'title' => 'Community',
                'description' => 'Society today has often ignored God\'s instructions about the place of the family in community transformation. Our prayer and conviction is to build strong and healthy families that raise a godly and Christ-like community for the glory of Christ Jesus.',
            ],
            [
                'title' => 'Global',
                'description' => 'This captures the family carrying a broader missional agenda that views the nations of the world as the target. The family is the center for discipleship where children are nurtured and developed to spread the fragrance of Christ to the entire world through good works. (Eph. 2:10)',
            ],
            [
                'title' => 'Partnership - You Can Do Something',
                'description' => 'Everyone can take part in this noble work. In Nehemiah 3, different people used their resources and influence to build sections of the walls. All of us are invited by the Lord to engage in building strong families through family-based discipleship.',
            ],
        ],
        'values' => [
            [
                'title' => 'The Supremacy of the Trinity',
                'description' => 'We honor the Father, Son, and Holy Spirit as supreme in life, family, church, and mission.',
            ],
            [
                'title' => 'The Lordship of Jesus Christ',
                'description' => 'We submit our work, message, and service to the Lordship of Jesus Christ.',
            ],
            [
                'title' => 'The Authority of the Bible',
                'description' => 'We look to Scripture as the authority for discipleship, family life, and transformation.',
            ],
            [
                'title' => 'The Body of Christ',
                'description' => 'We recognize accountability through authentic fellowship in the Body of Christ.',
            ],
            [
                'title' => 'Family Discipleship',
                'description' => 'We affirm the role of the family in the discipleship mandate.',
            ],
            [
                'title' => 'The Missional Family',
                'description' => 'We believe the family carries a missional agenda for communities and nations.',
            ],
        ],
        'objectives' => [
            [
                'title' => 'Strong Marriages and Families',
                'description' => 'Godly and healthy homes living out Bible truth.',
            ],
            [
                'title' => 'Community Transformation',
                'description' => 'Godly offspring influencing the people around them.',
            ],
            [
                'title' => 'Global Missional Discipleship',
                'description' => 'Fruitful evangelization of the world with the Gospel.',
            ],
        ],
        'contact' => [
            'phone' => '+254 115 679 375',
            'email' => 'buildingfams.global@gmail.com',
            'location' => 'Office: Tharaka Nithi - Chuka, Kenya. P.O. Box 60400-417',
            'hours' => 'Monday - Friday, 9:00 AM - 6:00 PM',
        ],
    ],
    'branding' => [
        'site_name' => 'BFC Global Trust',
        'tagline' => 'Family and Community Care',
        'logo_url' => '',
        'favicon_url' => '/favicon.ico',
        'join_label' => 'Join Us',
        'join_url' => '/get-involved',
        'donate_label' => 'Donate',
        'donate_url' => '/donate',
    ],
    'whatsapp' => [
        'enabled' => false,
        'phone' => '+254115679375',
        'message' => 'Hello BFC Global Trust, I would like to connect with your team.',
        'label' => 'Chat on WhatsApp',
    ],
    'navigation' => [
        ['label' => 'Home', 'path' => '/'],
        ['label' => 'About', 'path' => '/about'],
        ['label' => 'Ministry Programs', 'path' => '/ministry-programs'],
        ['label' => 'Events', 'path' => '/events'],
        ['label' => 'Gallery', 'path' => '/gallery'],
        ['label' => 'Resources Hub', 'path' => '/resources-hub'],
        ['label' => 'Blog', 'path' => '/blog'],
        ['label' => 'Get Involved', 'path' => '/get-involved'],
        ['label' => 'Contact', 'path' => '/contact'],
    ],
    'home_about' => [
        'eyebrow' => 'About Us',
        'title' => 'Building families, touching communities, changing the world',
        'scripture_reference' => 'Nehemiah 2:18',
        'scripture_text' => 'Then I said to them, "You see the trouble we are in: Jerusalem lies in ruins, and its gates have been burned with fire. Come, let us rebuild the wall of Jerusalem, and we will no longer be in disgrace." I also told them about the gracious hand of my God on me and what the king had said to me. They replied, "Let us start rebuilding." So they began this good work.',
        'image' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
        'image_alt' => 'Families and community members gathered in support',
        'primary_label' => 'Learn More',
        'primary_url' => '/about',
        'secondary_label' => 'Contact Us',
        'secondary_url' => '/contact',
    ],
    'home_hero_slides' => [
        [
            'id' => 'marriage-hope',
            'eyebrow' => 'Hope Restored',
            'title' => 'Is your marriage over? It does not have to be.',
            'description' => 'Receive compassionate, faith-rooted support that helps couples heal, reconnect, and rebuild trust.',
            'image' => 'https://images.unsplash.com/photo-1516589091380-5d8e87df6999?auto=format&fit=crop&w=2000&q=80',
            'primary_cta' => ['label' => 'Contact Our Team', 'to' => '/contact'],
            'secondary_cta' => ['label' => 'Ministry Programs', 'to' => '/ministry-programs'],
        ],
        [
            'id' => 'parenting-confidence',
            'eyebrow' => 'Parenting Support',
            'title' => 'Parenting is hard. You do not have to figure it out alone.',
            'description' => 'Practical tools, coaching, and community circles that bring calm, confidence, and healthy family rhythms.',
            'image' => 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=2000&q=80',
            'primary_cta' => ['label' => 'Explore Resources', 'to' => '/resources-hub'],
            'secondary_cta' => ['label' => 'Talk to Our Team', 'to' => '/contact'],
        ],
        [
            'id' => 'youth-future',
            'eyebrow' => 'Youth Programs',
            'title' => 'Every young person deserves guidance, belonging, and purpose.',
            'description' => 'Mentorship, tutoring, and leadership pathways that help youth discover identity and prepare for a hopeful future.',
            'image' => 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=2000&q=80',
            'primary_cta' => ['label' => 'View Ministry Programs', 'to' => '/ministry-programs'],
            'secondary_cta' => ['label' => 'Volunteer as Mentor', 'to' => '/get-involved'],
        ],
    ],
    'featured_resources' => [
        [
            'title' => 'Calm Mornings Toolkit',
            'description' => 'Five simple routines that lower stress and improve school-day transitions for children and caregivers.',
            'category' => 'Parenting Basics',
            'read_time' => '7 min read',
        ],
        [
            'title' => 'Marriage Check-In Guide',
            'description' => 'A weekly conversation framework for couples to reconnect emotionally, spiritually, and practically.',
            'category' => 'Marriage Support',
            'read_time' => '9 min read',
        ],
        [
            'title' => 'Teen Purpose Planner',
            'description' => 'A printable reflection and goal worksheet designed for youth identity, confidence, and healthy decision making.',
            'category' => 'Youth Development',
            'read_time' => '6 min read',
        ],
    ],
    'impact_stats' => [
        ['value' => '1,850+', 'label' => 'Families Served Last Year'],
        ['value' => '320', 'label' => 'Youth in Weekly Mentoring'],
        ['value' => '94%', 'label' => 'Parents Reporting Better Communication'],
        ['value' => '46', 'label' => 'Community Partners and Churches'],
    ],
    'testimonials' => [
        [
            'quote' => 'Our home felt tense all the time. After the parenting circle, we learned how to listen first and correct with calm. Our evenings are peaceful now.',
            'name' => 'Marissa T.',
            'role' => 'Parent of Two',
            'image' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
            'detail' => 'Before joining the parenting circle, our evenings were filled with stress and repeated arguments. The team helped us slow down, listen first, and build simple routines our children could trust. We still have normal family challenges, but now we repair faster and communicate with more patience.',
        ],
        [
            'quote' => 'The marriage coaching sessions helped us rebuild trust after a hard season. We now have tools we actually use every week.',
            'name' => 'Daniel & Ruth A.',
            'role' => 'Program Participants',
            'image' => 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=200&q=80',
            'detail' => 'We came into coaching feeling tired, defensive, and unsure how to move forward. The sessions gave us structure for honest conversations, forgiveness, and weekly check-ins. The biggest change is that conflict no longer feels like the end of the story; we know how to pause, pray, and repair.',
        ],
        [
            'quote' => 'My son joined the youth leadership track and discovered confidence he did not know he had. The mentors changed his direction.',
            'name' => 'Angela P.',
            'role' => 'Community Member',
            'image' => 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
            'detail' => 'My son needed adults who could see his potential and keep showing up. Through mentoring, service projects, and leadership sessions, he learned to set goals and speak with confidence. He is more engaged at school, more hopeful about his future, and proud of the person he is becoming.',
        ],
    ],
    'parenting_tips' => [
        'Lead with connection before correction to keep your child open to guidance.',
        'Set predictable routines for bedtime, homework, and screen use to reduce conflict.',
        'Use short family meetings once a week to celebrate wins and solve challenges together.',
        'Model emotional language: name feelings calmly so children can learn regulation.',
        'Create one-on-one moments with each child, even if only 10 focused minutes daily.',
    ],
    'family_support_programs' => [
        [
            'title' => 'Parent Circles',
            'description' => 'Small, guided groups that provide practical tools for discipline, communication, and child development.',
            'schedule' => 'Tuesdays and Thursdays',
        ],
        [
            'title' => 'Couples Growth Track',
            'description' => 'Eight-week sessions covering conflict repair, emotional intimacy, finances, and shared spiritual rhythms.',
            'schedule' => 'Saturday mornings',
        ],
        [
            'title' => 'Family Care Navigation',
            'description' => 'Personalized support to connect families with counseling, housing referrals, food support, and emergency planning.',
            'schedule' => 'By appointment',
        ],
    ],
    'outreach_initiatives' => [
        [
            'name' => 'Neighborhood Family Nights',
            'description' => 'Monthly events featuring parenting workshops, youth games, meals, and resource booths in local community centers.',
        ],
        [
            'name' => 'School Partnership Program',
            'description' => 'Mentoring and parent education sessions co-hosted with school counselors and teacher leaders.',
        ],
        [
            'name' => 'Care Closet Collaborative',
            'description' => 'A coordinated network for distributing diapers, hygiene kits, school supplies, and household essentials.',
        ],
        [
            'name' => 'Faith & Family Roundtables',
            'description' => 'Citywide conversations that equip leaders to support families in culturally wise and practical ways.',
        ],
    ],
    'youth_programs' => [
        [
            'title' => 'Pathfinders Mentorship',
            'age' => 'Ages 12 - 18',
            'description' => 'One-on-one mentoring and life coaching focused on confidence, character, and future planning.',
        ],
        [
            'title' => 'After-School Homework Hub',
            'age' => 'Ages 10 - 16',
            'description' => 'Academic support, study skills, and peer encouragement with trained tutors and volunteers.',
        ],
        [
            'title' => 'Creative Voices Studio',
            'age' => 'Ages 13 - 19',
            'description' => 'Music, storytelling, and visual arts workshops that help young people process emotions and build healthy identity.',
        ],
        [
            'title' => 'Young Leaders Service Lab',
            'age' => 'Ages 15 - 21',
            'description' => 'Hands-on community service projects that develop leadership, teamwork, and civic responsibility.',
        ],
    ],
    'counseling_services' => [
        [
            'slug' => 'family-counseling',
            'title' => 'Family Counseling',
            'description' => 'Support for parent-child conflict, transitions, grief, and communication breakdowns.',
            'overview' => 'Family counseling creates a guided space for households to slow down, listen well, repair trust, and develop healthier patterns of communication.',
            'who_for' => [
                'Parents and children navigating repeated conflict',
                'Families facing grief, separation, relocation, or major transitions',
                'Households needing practical rhythms for communication and discipline',
            ],
            'what_to_expect' => [
                'A confidential intake conversation to understand the family story',
                'Shared goals for healing, repair, and practical next steps',
                'Guided sessions with tools to practice between meetings',
            ],
            'outcomes' => [
                'Improved communication and emotional safety',
                'Clearer family routines and expectations',
                'Stronger connection between parents, caregivers, and children',
            ],
        ],
        [
            'slug' => 'couples-counseling',
            'title' => 'Couples Counseling',
            'description' => 'Guided care for conflict recovery, trust restoration, and relationship resilience.',
            'overview' => 'Couples counseling helps partners rebuild trust, strengthen communication, and develop shared rhythms for conflict repair, intimacy, and family leadership.',
            'who_for' => [
                'Couples experiencing frequent conflict or emotional distance',
                'Partners seeking trust restoration after a painful season',
                'Married or engaged couples desiring stronger biblical foundations',
            ],
            'what_to_expect' => [
                'A careful assessment of communication, trust, and shared goals',
                'Practical exercises for listening, repair, and decision making',
                'Support that honors marriage, family, faith, and accountability',
            ],
            'outcomes' => [
                'Healthier conflict repair and emotional honesty',
                'Renewed trust, patience, and shared purpose',
                'Stronger partnership in parenting, finances, and discipleship',
            ],
        ],
        [
            'slug' => 'youth-emotional-support',
            'title' => 'Youth Emotional Support',
            'description' => 'Age-appropriate counseling for anxiety, stress, identity, and school-related pressures.',
            'overview' => 'Youth emotional support provides age-sensitive guidance for young people facing anxiety, stress, identity questions, peer pressure, and school-related burdens.',
            'who_for' => [
                'Young people experiencing anxiety, stress, or withdrawal',
                'Students navigating identity, purpose, or peer pressure',
                'Families seeking wise support for youth emotional wellbeing',
            ],
            'what_to_expect' => [
                'A safe and respectful space for young people to be heard',
                'Practical coping tools for stress, choices, and relationships',
                'Parent or caregiver guidance where appropriate',
            ],
            'outcomes' => [
                'Improved confidence and emotional language',
                'Healthier decision making and peer relationships',
                'Greater sense of purpose, belonging, and resilience',
            ],
        ],
        [
            'slug' => 'crisis-stabilization-care',
            'title' => 'Crisis and Stabilization Care',
            'description' => 'Immediate support planning, referrals, and wraparound follow-up for urgent family needs.',
            'overview' => 'Crisis and stabilization care helps families identify immediate needs, create a short-term safety plan, and connect with trusted referrals and follow-up support.',
            'who_for' => [
                'Families facing urgent conflict, loss, or instability',
                'Households needing referral support and care coordination',
                'People unsure which support pathway is the best next step',
            ],
            'what_to_expect' => [
                'A focused intake to clarify immediate concerns and risk level',
                'Support planning, referrals, and practical next steps',
                'Follow-up care to help the family move toward stability',
            ],
            'outcomes' => [
                'Clear next steps during a difficult moment',
                'Connection to trusted resources and care partners',
                'A more stable pathway for ongoing support',
            ],
        ],
    ],
    'involvement_opportunities' => [
        [
            'title' => 'Volunteer Mentor',
            'description' => 'Walk alongside youth and families through consistent encouragement and practical support.',
        ],
        [
            'title' => 'Program Facilitator',
            'description' => 'Lead workshops in parenting, marriage enrichment, budgeting, career readiness, or faith formation.',
        ],
        [
            'title' => 'Community Advocate',
            'description' => 'Help coordinate local events, neighborhood partnerships, and outreach campaigns.',
        ],
        [
            'title' => 'Prayer & Care Team',
            'description' => 'Support families through check-ins, care packages, and faithful encouragement.',
        ],
    ],
    'events' => [
        [
            'slug' => 'family-discipleship-workshop',
            'title' => 'Family Discipleship Workshop',
            'date' => 'June 15, 2026',
            'time' => '9:00 AM - 1:00 PM',
            'location' => 'BFC Global Trust Training Hall',
            'category' => 'Training',
            'description' => 'A practical equipping session for parents, ministry leaders, and caregivers on restoring discipleship in the home.',
            'image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
            'registration_open' => true,
        ],
        [
            'slug' => 'marriage-and-family-forum',
            'title' => 'Marriage and Family Forum',
            'date' => 'July 6, 2026',
            'time' => '2:00 PM - 5:00 PM',
            'location' => 'Community Fellowship Center',
            'category' => 'Family Life',
            'description' => 'A guided forum for couples and families to reflect on biblical foundations, healing, and healthy family rhythms.',
            'image' => 'https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=1200&q=80',
            'registration_open' => true,
        ],
        [
            'slug' => 'youth-leadership-gathering',
            'title' => 'Youth Purpose and Leadership Gathering',
            'date' => 'August 10, 2026',
            'time' => '10:00 AM - 3:00 PM',
            'location' => 'Partner Learning Institution',
            'category' => 'Youth',
            'description' => 'A gathering for young people focused on identity, discipleship, leadership, and influence in learning institutions.',
            'image' => 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
            'registration_open' => true,
        ],
    ],
    'donation_settings' => [
        'options_eyebrow' => 'Giving Options',
        'options_heading' => 'Where your donation can go',
        'heading' => 'Make a Donation',
        'description' => 'Complete the form first, then use PayPal to securely finish your gift.',
        'program_default_label' => 'General Family Support',
        'preset_amounts' => [25, 50, 100],
        'show_programs' => true,
        'show_events' => true,
        'allow_monthly' => true,
        'paypal_enabled' => (bool) env('PAYPAL_CLIENT_ID', false),
        'paypal_mode' => 'sandbox',
        'paypal_client_id' => env('PAYPAL_CLIENT_ID', ''),
        'paypal_secret' => env('PAYPAL_SECRET', ''),
        'paypal_currency' => env('PAYPAL_CURRENCY', 'USD'),
        'paypal_help_text' => 'PayPal checkout is ready to enable. Add your PayPal Client ID in Donation Management to show the PayPal payment button.',
        'giving_options' => [
            [
                'title' => 'Programs',
                'description' => 'Support parenting resources, marriage care, youth mentoring, counseling, or outreach.',
            ],
            [
                'title' => 'Events',
                'description' => 'Sponsor workshops, family nights, school partnerships, and community care events.',
            ],
            [
                'title' => 'General Fund',
                'description' => 'Give flexibly so the team can respond where needs are most urgent.',
            ],
        ],
    ],
    'gallery_photos' => [
        [
            'title' => 'Campus Discipleship Fellowship',
            'category' => 'Campus Ministry',
            'image' => 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Family Discipleship Workshop',
            'category' => 'Family Training',
            'image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Prayer and Family Worship',
            'category' => 'Worship',
            'image' => 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'slug' => 'youth-leadership-gathering',
            'title' => 'Youth Leadership Gathering',
            'category' => 'Youth Programs',
            'image' => 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Community Outreach Day',
            'category' => 'Outreach',
            'image' => 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Ministry Training Session',
            'category' => 'Training in Ministry',
            'image' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Marriage and Family Forum',
            'category' => 'Marriage & Family',
            'image' => 'https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=1200&q=80',
        ],
        [
            'title' => 'Discipleship Resource Table',
            'category' => 'Resource Hub',
            'image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80',
        ],
    ],
    'event_registration_questions' => [
        [
            'key' => 'attendance_goal',
            'label' => 'What do you hope to gain from this event?',
            'required' => true,
        ],
        [
            'key' => 'attendee_count',
            'label' => 'How many people are you registering for?',
            'required' => false,
        ],
        [
            'key' => 'special_notes',
            'label' => 'Any questions, accessibility needs, or special notes?',
            'required' => false,
        ],
    ],
    'resources_hub' => [
        [
            'title' => 'Christian Literature',
            'description' => 'Biblical books, discipleship guides, family devotion materials, and Christian reading resources for homes, schools, Christian Unions, and churches.',
            'image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80',
            'button_label' => 'Purchase Books',
            'button_url' => '/shop',
        ],
        [
            'title' => 'Program Videos',
            'description' => 'Recorded teachings, training highlights, discipleship conversations, ministry updates, and practical program videos for continued learning.',
            'image' => 'https://images.unsplash.com/photo-1497015289639-54688650d173?auto=format&fit=crop&w=1200&q=80',
            'button_label' => 'Watch Videos',
            'button_url' => '/resources-hub/videos',
        ],
        [
            'title' => 'Sermons',
            'description' => 'Faith-building sermons and biblical messages that strengthen families, young people, Christian leaders, and the church in discipleship.',
            'image' => 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&w=1200&q=80',
            'button_label' => 'Open Sermons',
            'button_url' => '/resources-hub/sermons',
        ],
        [
            'title' => 'Family Board Games',
            'description' => 'Bonding indoor games and family-friendly discipleship tools that help homes connect, learn, laugh, and grow together.',
            'image' => 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80',
        ],
    ],
    'sermons' => [
        'daily' => [
            [
                'title' => 'Daily Family Altar',
                'date' => 'Monday',
                'speaker' => 'BFC Global Trust Team',
                'description' => 'A short daily encouragement for prayer, Scripture reflection, and family discipleship.',
                'url' => 'https://www.youtube.com/',
            ],
            [
                'title' => 'Morning Word for Parents',
                'date' => 'Tuesday',
                'speaker' => 'BFC Global Trust Team',
                'description' => 'Daily biblical encouragement for parenting with patience, wisdom, and faith.',
                'url' => 'https://www.youtube.com/',
            ],
        ],
        'weekly' => [
            [
                'title' => 'Building Strong Homes',
                'date' => 'Week 1',
                'speaker' => 'Philemon',
                'description' => 'A weekly sermon on discipleship rhythms that strengthen marriage, parenting, and community life.',
                'url' => 'https://www.youtube.com/',
            ],
            [
                'title' => 'The Family as a Discipleship Center',
                'date' => 'Week 2',
                'speaker' => 'BFC Global Trust Team',
                'description' => 'Teaching on restoring biblical discipleship in the home and church.',
                'url' => 'https://www.youtube.com/',
            ],
        ],
    ],
    'book_products' => [
        [
            'slug' => 'family-discipleship-guide',
            'title' => 'Family Discipleship Guide',
            'author' => 'BFC Global Trust',
            'category' => 'Christian Literature',
            'description' => 'A practical PDF guide for building discipleship rhythms in the home through prayer, Scripture, conversation, and family practices.',
            'price' => 12,
            'currency' => 'USD',
            'cover_image' => 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1200&q=80',
            'format' => 'pdf',
            'pdf_url' => '',
            'purchase_url' => '/donate',
            'is_available' => true,
        ],
        [
            'slug' => 'parental-discipleship-workbook',
            'title' => 'Parental Discipleship Workbook',
            'author' => 'BFC Global Trust',
            'category' => 'Parenting',
            'description' => 'Workbook-style material for parents seeking biblical encouragement, practical reflection prompts, and family discipleship tools.',
            'price' => 15,
            'currency' => 'USD',
            'cover_image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80',
            'format' => 'pdf',
            'pdf_url' => '',
            'purchase_url' => '/donate',
            'is_available' => true,
        ],
    ],
    'program_videos' => [
        [
            'title' => 'BUILD Discipleship Introduction',
            'description' => 'An introductory teaching on the heart of family discipleship and community transformation.',
            'category' => 'Teaching',
            'thumbnail' => 'https://images.unsplash.com/photo-1497015289639-54688650d173?auto=format&fit=crop&w=1200&q=80',
            'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        ],
        [
            'title' => 'Family Discipleship Conversation',
            'description' => 'A practical conversation on building rhythms of prayer, teaching, and care within the home.',
            'category' => 'Family Training',
            'thumbnail' => 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
            'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        ],
        [
            'title' => 'Youth Mentorship Highlight',
            'description' => 'A ministry update highlighting mentorship, leadership, and discipleship among young people.',
            'category' => 'Youth Programs',
            'thumbnail' => 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80',
            'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        ],
    ],
    'ministry_programs' => [
        [
            'slug' => 'build-campus-discipleship',
            'title' => 'BUILD - Campus Discipleship',
            'menu_label' => 'BUILD - Campus Discipleship',
            'audience' => 'Campus Students',
            'format' => 'One-to-one discipleship, preaching engagements, and Christian Union partnerships',
            'description' => 'We share the Gospel and disciple campus students through a one-to-one approach. We also accept preaching engagements from Christian Unions in partnership with Focus Kenya and other ministries.',
            'registration' => [
                'open' => true,
                'button_label' => 'Register',
                'intro' => 'Choose the campus discipleship intake that fits you and tell us about your campus or Christian Union context.',
                'cohorts' => ['May 2026 Intake', 'June 2026 Intake', 'Christian Union Partnership'],
                'questions' => [
                    ['key' => 'campus_or_cu', 'label' => 'Which campus, college, or Christian Union are you connected to?', 'required' => true],
                    ['key' => 'discipleship_need', 'label' => 'What kind of discipleship support are you seeking?', 'required' => true],
                ],
            ],
        ],
        [
            'slug' => 'build-high-school-discipleship',
            'title' => 'BUILD - High School Discipleship',
            'menu_label' => 'BUILD - High School Discipleship',
            'audience' => 'High School Students',
            'format' => 'Biblical teaching, preaching, leadership training, and weekend challenges',
            'description' => 'We partner with Christian Union patrons and high schools for biblical teachings, Sunday services, and weekly discipleship platforms. We also partner and network with KSCF for effective ministry among high school students.',
        ],
        [
            'slug' => 'build-discipleship-series',
            'title' => 'BUILD - Discipleship Series',
            'menu_label' => 'BUILD - Discipleship Series',
            'audience' => 'Campus Students and Young Professionals',
            'format' => 'Online discipleship initiative',
            'description' => 'Apart from the institutional strategies, this online discipleship initiative is tailor-made for campus students and busy young professionals locally and abroad, including delegates in Scotland, the United States, and the United Arab Emirates. These efforts have brought encouragement to delegates in places where the Word of God is rare.',
        ],
        [
            'slug' => 'build-the-man',
            'title' => 'BUILD the Man',
            'menu_label' => 'BUILD the Man',
            'subtitle' => 'Discipleship Conversation',
            'audience' => 'Young Men: Married, Courting, or Single',
            'format' => '10-week virtual discipleship training',
            'description' => 'A discipleship conversation designed for like-minded men working toward the restoration of biblical manhood. Guided by Scripture, this community works to biblically empower every man, young and older, to seek freedom and come together for a corporate confrontation of the issues that affect men today.',
        ],
        [
            'slug' => 'build-the-woman',
            'title' => 'BUILD the Woman',
            'menu_label' => 'BUILD the Woman',
            'subtitle' => 'Discipleship Conversation',
            'audience' => 'Women: Married, Courting, or Single',
            'format' => '10-week virtual discipleship training',
            'description' => 'A discipleship conversation designed for like-minded women working toward the restoration of biblical womanhood. Guided by Scripture, this community works to biblically empower every woman, young and older, to seek freedom and come together for a corporate confrontation of the issues that affect women today.',
        ],
        [
            'slug' => 'build-premarital-discipleship',
            'title' => 'Build - Premarital Discipleship',
            'menu_label' => 'Build - Premarital Discipleship',
            'audience' => 'Courting Young People',
            'format' => '12-week discipleship series',
            'description' => 'A discipleship series that prepares and challenges courting young people toward Christ-centered marriages, with greater emphasis on discipleship than a formality-based counseling approach.',
        ],
        [
            'slug' => 'build-prayer-family-worship',
            'title' => 'Build - Prayer & Family Worship',
            'menu_label' => 'Build - Prayer & Family Worship',
            'audience' => 'Families and Young People',
            'format' => 'Prayer, worship, and fellowship',
            'description' => 'A fellowship of like-minded families and young people, married, courting, or single, coming together for prayer and worship while modeling practical Christian living in marriage and family.',
        ],
        [
            'slug' => 'build-parental-discipleship',
            'title' => 'Build - Parental Discipleship',
            'menu_label' => 'Build - Parental Discipleship',
            'audience' => 'Parents',
            'format' => 'Monthly discipleship program',
            'description' => 'A monthly discipleship program designed to give parents hope, encouragement, and consistent learning for family discipleship.',
        ],
        [
            'slug' => 'build-play-connect',
            'title' => 'Build - Play & Connect',
            'menu_label' => 'Build - Play & Connect',
            'audience' => 'Young Professionals and Campus Students',
            'format' => 'Short Bible studies, board games, and creative Bible trivia',
            'description' => 'A relational strategy that gathers young professionals and campus students around short Bible studies, board games, and creative Bible trivia.',
        ],
        [
            'slug' => 'training-in-ministry-tim-1',
            'title' => 'Training in Ministry (TiM-1)',
            'menu_label' => 'Training in Ministry (TiM-1)',
            'audience' => 'Campus and College Leavers',
            'format' => '13-week residential character and discipleship training',
            'description' => 'A residential program for campus and college leavers who are on long holiday or have just cleared tertiary education, focused on character formation and discipleship.',
        ],
        [
            'slug' => 'training-in-ministry-tim-2',
            'title' => 'Training in Ministry (TiM-2)',
            'menu_label' => 'Training in Ministry (TiM-2)',
            'audience' => 'Campus and College Leavers',
            'format' => 'One-year internship and volunteer program',
            'description' => 'A one-year internship and volunteer pathway that gives campus and college leavers an opportunity for deeper and thorough ministry training.',
        ],
        [
            'slug' => 'build-discipleship-resource-hub',
            'title' => 'Build - Discipleship & Resource Hub',
            'menu_label' => 'Build - Discipleship & Resource Hub',
            'audience' => 'Schools, Christian Unions, Churches, Homes, and Families',
            'format' => 'Christian literature and family bonding resources',
            'description' => 'We equip schools, Christian Unions, and churches with Christian literature, and homes and families with bonding indoor games and discipleship resources.',
        ],
    ],
    'marriage_pillars' => [
        [
            'title' => 'Healthy Communication',
            'description' => 'Learn active listening, emotional validation, and conflict de-escalation tools that protect connection.',
        ],
        [
            'title' => 'Shared Purpose',
            'description' => 'Clarify family values, parenting goals, and long-term vision so couples move forward with unity.',
        ],
        [
            'title' => 'Financial Partnership',
            'description' => 'Build collaborative money habits with budgeting rhythms, honest conversations, and practical planning.',
        ],
        [
            'title' => 'Faith and Resilience',
            'description' => 'Develop spiritual practices and support systems that sustain marriages through life pressures.',
        ],
    ],
    'youth_outcomes' => [
        'Improved confidence and emotional regulation',
        'Higher school engagement and clearer goals',
        'Healthy peer relationships and leadership growth',
        'Increased service mindset and civic responsibility',
    ],
    'counseling_steps' => [
        [
            'title' => '1. Initial Connection',
            'detail' => 'Submit a support inquiry and our care team schedules a confidential intake conversation.',
        ],
        [
            'title' => '2. Personalized Care Plan',
            'detail' => 'We identify immediate needs, goals, and recommended support options for your family.',
        ],
        [
            'title' => '3. Ongoing Support',
            'detail' => 'Families receive counseling sessions, practical resources, and progress check-ins.',
        ],
    ],
    'outreach_focus_areas' => [
        'Family resource distribution and referral access',
        'Parent education events in neighborhood hubs',
        'Collaborative care with schools and local leaders',
        'Faith-based support networks for vulnerable households',
    ],
    'blog_posts' => [
        [
            'slug' => '5-evening-routines-that-reduce-family-stress',
            'title' => '5 Evening Routines That Reduce Family Stress',
            'excerpt' => 'Simple patterns that help families reconnect after long days and make bedtime smoother for everyone.',
            'category' => 'Parenting',
            'image' => 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Naomi Carter',
            'date_label' => 'March 4, 2026',
            'published_at' => '2026-03-04',
            'read_time' => '8 min read',
            'content' => [
                [
                    'heading' => 'Why Evenings Matter',
                    'paragraphs' => [
                        'Evenings often carry leftover pressure from work, school, and commuting. Without a shared rhythm, stress compounds and small conflicts escalate quickly.',
                        'A steady routine helps children regulate emotions and gives caregivers fewer decisions to make while tired. The result is more connection and less chaos.',
                    ],
                ],
                [
                    'heading' => 'A Practical Routine to Try',
                    'paragraphs' => [
                        'Start with a 15-minute reset: everyone puts away one item, washes hands, and shares one high and one low from the day.',
                        'Create a visible sequence for dinner, prep for tomorrow, calm play, prayer or reflection, and bedtime. Keep expectations realistic and celebrate progress instead of perfection.',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'how-couples-can-rebuild-trust-after-conflict',
            'title' => 'How Couples Can Rebuild Trust After Conflict',
            'excerpt' => 'Restoring trust is a process. Learn four repeatable habits that bring healing over time.',
            'category' => 'Marriage',
            'image' => 'https://images.unsplash.com/photo-1484863137850-59afcfe05386?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Marcus Lee',
            'date_label' => 'February 20, 2026',
            'published_at' => '2026-02-20',
            'read_time' => '10 min read',
            'content' => [
                [
                    'heading' => 'Trust Is Repaired in Small Moments',
                    'paragraphs' => [
                        'Big apologies matter, but consistency in daily actions is what restores safety. Keep promises simple and specific.',
                        'When hurt resurfaces, respond with patience instead of defensiveness. This builds a new pattern of care.',
                    ],
                ],
                [
                    'heading' => 'Four Habits That Help',
                    'paragraphs' => [
                        'Use weekly check-ins, transparent communication, shared boundaries, and outside support when needed.',
                        'A healthy relationship does not avoid conflict. It learns how to repair with humility, honesty, and hope.',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'mentoring-teens-with-purpose-and-grace',
            'title' => 'Mentoring Teens with Purpose and Grace',
            'excerpt' => 'Young people thrive when adults combine high expectations with meaningful encouragement.',
            'category' => 'Youth',
            'image' => 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Jordan Ellis',
            'date_label' => 'January 29, 2026',
            'published_at' => '2026-01-29',
            'read_time' => '7 min read',
            'content' => [
                [
                    'heading' => 'Teens Need Belonging Before Advice',
                    'paragraphs' => [
                        'Mentorship starts with relationship, not lectures. A young person who feels seen is more open to challenge and growth.',
                        'Simple consistency, like weekly texts and showing up to activities, communicates unwavering support.',
                    ],
                ],
                [
                    'heading' => 'Build a Growth Path Together',
                    'paragraphs' => [
                        'Set one short-term and one long-term goal, then review monthly. Let teens identify obstacles and choose next steps.',
                        'Celebrate effort, not just outcomes. This develops resilience and internal motivation.',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'supporting-children-through-major-transitions',
            'title' => 'Supporting Children Through Major Transitions',
            'excerpt' => 'From school changes to family moves, learn how to help children feel safe during uncertainty.',
            'category' => 'Family Life',
            'image' => 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Renee Hall',
            'date_label' => 'January 15, 2026',
            'published_at' => '2026-01-15',
            'read_time' => '9 min read',
            'content' => [
                [
                    'heading' => 'Name What Is Changing',
                    'paragraphs' => [
                        'Children notice more than adults assume. Naming change honestly reduces fear and confusion.',
                        'Use age-appropriate language and invite questions repeatedly, not just once.',
                    ],
                ],
                [
                    'heading' => 'Protect Anchors',
                    'paragraphs' => [
                        'Keep stable routines such as mealtime, bedtime rituals, and family prayer or reflection.',
                        'When familiar anchors stay in place, children regain emotional balance faster.',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'building-community-partnerships-that-last',
            'title' => 'Building Community Partnerships That Last',
            'excerpt' => 'Strong partnerships are built on trust, shared goals, and practical coordination.',
            'category' => 'Community Outreach',
            'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Lydia Freeman',
            'date_label' => 'December 18, 2025',
            'published_at' => '2025-12-18',
            'read_time' => '6 min read',
            'content' => [
                [
                    'heading' => 'Start with Shared Priorities',
                    'paragraphs' => [
                        'Partnerships become sustainable when organizations define one or two clear outcomes together.',
                        'Shared ownership prevents duplicated effort and creates accountability.',
                    ],
                ],
                [
                    'heading' => 'Communicate with Rhythm',
                    'paragraphs' => [
                        'Use monthly partner huddles, transparent data points, and rapid follow-up for families with urgent needs.',
                        'When communication is predictable, collaboration stays healthy even during high-demand seasons.',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'when-to-seek-family-counseling-and-what-to-expect',
            'title' => 'When to Seek Family Counseling and What to Expect',
            'excerpt' => 'Counseling is a courageous next step. Here is how to know when support may help and what sessions look like.',
            'category' => 'Counseling',
            'image' => 'https://images.unsplash.com/photo-1573496799515-eebbb63814f2?auto=format&fit=crop&w=1200&q=80',
            'author' => 'Dr. Selina Brooks',
            'date_label' => 'November 26, 2025',
            'published_at' => '2025-11-26',
            'read_time' => '11 min read',
            'content' => [
                [
                    'heading' => 'Common Signs It Is Time',
                    'paragraphs' => [
                        'Persistent conflict, emotional withdrawal, school behavior changes, and caregiver burnout are all signals worth paying attention to.',
                        'Seeking help early can prevent patterns from becoming deeper and harder to repair.',
                    ],
                ],
                [
                    'heading' => 'What Sessions Often Include',
                    'paragraphs' => [
                        'Counseling usually begins with assessment, goal setting, and practical strategies that families practice between sessions.',
                        'Progress is not always linear, but steady support creates new skills and stronger relationships over time.',
                    ],
                ],
            ],
        ],
    ],
];
